site_name: JupyterLab DataMount
site_description: JupyterLab DataMount Documentation
site_author: EOSC Beyond, Juelich Supercomputing Centre
repo_url: https://github.com/jsc-jupyter/jupyterlab-data-mount
theme:
  name: material
  features:
    - nagivation.tabs
    - navigation.sections
    - navigation.collapse
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: images/jupyter-cloud-storage-icon.svg
  font:
    text: Fira Sans
    code: Roboto Mono
    icon: "mdi"
  favicon: images/jupyter-cloud-storage-icon.svg
  custom_dir: docs/custom
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
      - Using the Extension: users/howto.md
      - Storage Templates:
          - B2Drop: users/templates/b2drop.md
          - AWS: users/templates/aws.md
          - S3-Compatible Storage: users/templates/s3.md
          - WebDAV: users/templates/webdav.md
          - Generic Storage: users/templates/generic.md
      - Troubleshooting & FAQ: users/faq.md
  - Architecture:
      - Overview: architecture/overview.md
      - Backend API: architecture/backend_api.md
  - JupyterHub Spawner:
      - Installation: spawner/installation.md
      - Configuration: spawner/configuration.md

plugins:
  - social
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - meta
  - tables
  - def_list
  - neoteroi.cards
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_css:
  - css/style.css
  - css/neoteroi-cards.css
  - css/extra.css

extra:
  logo: "images/logo.png"
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jsc-jupyter/jupyterlab-data-mount
  footer:
    logo:
      link: https://eosc.eu/eu-project/eosc-beyond/
      img: images/EOSC-Beyond-logo.png
    copyright: |
      &copy; 2025 Forschungszentrum Jülich
    lines:
      - "Partially funded by ..."
      - "Grant Number ..."
    links:
      - name: Contact
        link: mailto:ds-support@fz-juelich.de?subject=JupyterLab DataMount
